export const COLLECTION_LOADING = "COLLECTION_LOADING";
export const COLLECTION_SUCCESS = "COLLECTION_SUCCESS";
export const COLLECTION_ERROR = "COLLECTION_ERROR";

export const ADD_COLLECTION_LOADING = "ADD_COLLECTION_LOADING";
export const ADD_COLLECTION_SUCCESS = "ADD_COLLECTION_SUCCESS";
export const ADD_COLLECTION_ERROR = "ADD_COLLECTION_ERROR";

export const DELETE_COLLECTION_LOADING = "DELETE_COLLECTION_LOADING";
export const DELETE_COLLECTION_SUCCESS = "DELETE_COLLECTION_SUCCESS";
export const DELETE_COLLECTION_ERROR = "DELETE_COLLECTION_ERROR";